### ISSUE TITLE
getSchema() and each() don't seem to handle anyOf

### ISSUE THREAD

**Issue by felixfbecker** [sagold/json-schema-library#11]
I have a schema with a top-level `anyOf` with a bunch of `$ref`s to definitions (essentially a union type).

My use case for `getSchema()` or `each()` is to let the library resolve which of the `anyOf` items match and give me the matching schema (resolved from `$ref`).

But all I am getting is `UnknownPropertyError` (`Could not find a valid schema for property `#` within object`) in `each()`, and `getSchema()` always just returns the root schema. `isValid()` however returns `true`.

If I change the `anyOf` to `oneOf` _and_ move it to a nested property instead of top-level, it works, but obviously that changes the semantics.

Would really love to use this helper, I've not found any JSON schema library that offers similar utility.

**Comment by sagold** [comment]
Hi.

Yes, the `oneOf`-property is the feature with the most attention, since i use it a lot. I will update the `anyOf`-property support according to your description, but i cannot tell you when exactly. As Looking at my calender, i will add the support either next week or in september. 

In the meantime, i could only point you to the gory details of adding your own modified _step_- or whatever-function and create your own core with this behaviour.

Cheers.

**Comment by sagold** [comment]
I released the additions with v4.0.0. Beware the api changes.
