### ISSUE TITLE
Support for future JSON Schema Drafts / Specifications

### ISSUE THREAD

**Issue by rkpasia** [sagold/json-schema-library#37]
Hello @sagold ,

Me and @tcompa, are opening this issue because the team behind [Fractal Analytics Platform](https://fractal-analytics-platform.github.io/), an open platform to perform analysis on high magnitude of data, is considering to introduce in one of its packages this great library as dependency.

Since having a new dependency is always something to consider, I would like to ask what are your plan to support future releases of JSON Schema specifications.

As far as my understanding goes, this library currently supports JSON Schema until "Draft 7" which has been around for quite a while until now. 

Do you have any plan to introduce the support for further iterations of the Schema? Like Draft 2019-09?
I'm considering the specs as defined by https://json-schema.org/specification-links.html

Any kind of insights on this matter would be helpful for our project! Thank you.

**Comment by sagold** [comment]
Hi there.

Yes, _json-schema-library_ currently support draft 4 -7. Draft 8 (2019-09) and later versions will be supported in the future. Support for Draft 8 has already started, but is now delayed in favor of api changes and different priorities.

Since adding a new Draft, especially Draft 8, adds a lot of breaking changes with hundreds of tests to fulfill I cannot guarantee that support for a new draft will arrive within this year. On the other hand, these breaking changes will simplify some feature implementations and I am looking forward to this udpate.

I hope this helps you in your decision. Let me know if you have further questions.

Cheers,
sagold

**Comment by tcompa** [comment]
Hello, thanks a lot for this clarification - it does answer our questions. From our side there's no need for additional information, thus feel free to close this issue if you'd like to. Cheers, Tommaso

**Comment by jy95** [comment]
Hello @sagold ,

In the context of my [docusaurus-json-schema-plugin](https://jy95.github.io/docusaurus-json-schema-plugin/) library, I was also considering that your library could help me with the `$recursiveRef` / `$dynamicRef` cases. Just wondering what are your plans for the future

Thanks in advance
